name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    
    if: ${{ hashFiles('**/*.xcodeproj', '**/*.xcworkspace') != '' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project JobFinder.xcodeproj
      - name: Build (Debug)
        run: xcodebuild -project JobFinder.xcodeproj -scheme Jo
