name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project JobFinder/JobFinder.xcodeproj
      - name: Build (Debug)
        run: xcodebuild -project JobFinder.xcodeproj -scheme JobFinder/JobFinder -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15'
